apiVersion: rcs.mycrd/v1alpha1
kind: RanChy
metadata:
  name: book-bazar-01
  namespace: default
spec:
  labels:
    owner: Hiranmoy
  deploymentSpec:
    name: hello
    replicas: 2
    image: hiranmoy36/book-bazar
    command: ["/root/binary","start"]
  serviceSpec:
    port: 8080