apiVersion: rcs.mycrd/v1alpha1
kind: RanChy
metadata:
  name: book-bazar
  namespace: default
spec:
  deletionPolicy: WipeOut
  deploymentSpec:
    replicas: 2
    deploymentImage: nginx:latest
  serviceSpec:
    serviceName: service-name
    serviceType: NodePort
    servicePort: 30001
  labels:
    label: laula
